### ISSUE TITLE
出现这个报错是怎么回事

### ISSUE THREAD

**Issue by jackw111** [superHao2000/autoCheck#1]
Traceback (most recent call last):
  File "/ql/data/scripts/superHao2000_autoCheck_master/main.py", line 27, in <module>
    modules = get_modules(package)
              ^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/superHao2000_autoCheck_master/main.py", line 17, in get_modules
    files = os.listdir(packages)
            ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'checkin'

**Comment by KyleLyric** [comment]
订阅没把checkin文件夹下到青龙，手动加一下就行
